version: "3"
services:
  backend:
    image: villa01/backend_p1_201900907:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    links:
      - "database:db"
    environment:
      MONGODB_URI: "mongodb://mongoadmin:secret@db:27017"


  database:
    container_name: database
    image: mongo:5.0.6-focal
    ports:
      - "27017:27017"
    volumes:
      - "./database/:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret

  frontend:
    container_name: frontend_calculator
    image: villa01/frontend_p1_201900907:latest
    restart: unless-stopped
    ports:
      - "80:80"


